### ISSUE TITLE
Deprecated ansible apt usage with loop

### ISSUE THREAD

**Issue by Byggvir** [Freifunk-Troisdorf/ansible.fftdf.supernode#17]
Change deprecated apt install from (line 128)

```
    - name: Install common required packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
        with_items: "{{ common_required_packages }}"
      register: aptupdates
```

to
```
    - name: Install common required packages
      apt:
        name: "{{ common_required_packages }}"
        state: present
        update_cache: yes
      register: aptupdates
```
